name: test
on:
  push:
    tags-ignore:
      - '**'
    branches-ignore:
      - 'release*'
    paths:
      - 'trigger.txt'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo helloworld
